name: flutter_assignment
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  draw: ^1.0.2
  provider: ^6.0.3
  url_launcher: ^6.1.2
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  mockito: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  hive_test: ^1.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Lato-Bold
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
    - family: Lato-Regular
      fonts:
        - asset: fonts/Lato-Regular.ttf